name: Sync to Hugging Face hub
on: 
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: add remote
        env:
          HF_TOKEN: ${{secrets.HF_TOKEN}}
        run: git remote add space https://huggingface.co/spaces/M7md-al7aris/demo1

      - name: push to hub
        env:
          HF_TOKEN: ${{secrets.HF_TOKEN}}
        run: git push --force https://huggingface.co/spaces/M7md-al7aris/demo1 main
     
